name: sign

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  sign:
    strategy:
      matrix:
        os: ['windows-2019', 'windows-2022']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Register Microsoft Office Subject Interface Packages
        run: regsvr32.exe /s sip/msosipx.dll

      - name: Setup AzureSignTool
        run: dotnet tool install --verbosity minimal --global azuresigntool --version 3.0.0

      - name: Sign PowerPoint Add-in Macro
        run: |
            AzureSignTool.exe sign `
            --file-digest sha256 `
            --timestamp-rfc3161 http://timestamp.digicert.com `
            --timestamp-digest sha256 `
            --azure-key-vault-url https://opensourcesigning.vault.azure.net `
            --azure-key-vault-tenant-id "${{ secrets.KEYVAULT_TENANT_ID }}" `
            --azure-key-vault-client-id "${{ secrets.KEYVAULT_CLIENT_ID }}" `
            --azure-key-vault-client-secret "${{ secrets.KEYVAULT_CLIENT_SECRET }}" `
            --azure-key-vault-certificate "goITSolutions-until-2024-01" `
            --verbose `
            bin/AddinPresentation.ppam

      - name: Publish signed macro
        uses: actions/upload-artifact@v3
        with:
          name: macro-${{ matrix.os }}
          path: bin/
